# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
        exclude: konux/mcp/helm/templates/
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: docs/
      - id: trailing-whitespace
        exclude: docs/
      - id: mixed-line-ending
        exclude: docs/
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        exclude: docs/
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        exclude: docs/
